#!/usr/bin/env ruby

require 'open3'
require 'bundler/setup'
require 'idevice'

outfile = ARGV.shift
if outfile.nil? or ARGV.shift
  $stderr.puts "Usage: #{File.basename $0} path/to/output.cpio" 
  exit(1)
end

frc = Idevice::FileRelayClient.attach
$stderr.puts "[.] Requesting crash reports"
len = 0
File.open(outfile, 'w') do |outf|
  Open3.popen3("cpio -t") do |w,r,e|
    begin
      frc.request_sources("CrashReporter") do |chunk|
        w.write(chunk)
        outf.write(chunk)
        len += chunk.size
      end
    ensure
      w.close
      puts "[+] Wrote #{len} bytes to #{outfile}",
           "Contents:",
           r.read

      r.close
    end
  end
end

