#!/usr/bin/env ruby
#
# Copyright (c) 2013 Eric Monti
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


require 'bundler/setup'
require 'idevice'

ipa_path = ARGV.shift
if ipa_path.nil? or ARGV.shift
  $stderr.puts "Usage: #{File.basename} /path/to/an.ipa"
  exit(1)
end

ipa = Pathname(ipa_path)

idev = Idevice::Idevice.attach

remote_path = Pathname("PublicStaging").join(ipa.basename)

afc = Idevice::AFCClient.attach(idevice:idev)
$stderr.puts "[.] Uploading #{ipa} to #{remote_path}"
afc.put_path(ipa.to_s, remote_path.to_s)

instpxy = Idevice::InstProxyClient.attach(idevice:idev)
$stderr.puts "[.] Requesting installation of #{remote_path}"
finished = false
instpxy.install(remote_path.to_s) do |name, status|
  p [name, status]
  finished = (status["Error"] or status["Status"] == "Complete")
end

while not finished
  #nop
end
