#!/usr/bin/env ruby

require 'bundler/setup'
require 'idevice'

appid = ARGV.shift
if appid.nil? or ARGV.shift
  $stderr.puts "Usage: #{File.basename} appid" 
  exit(1)
end

instpxy = Idevice::InstProxyClient.attach
$stderr.puts "[.] Requesting uninstallation of #{appid}"
finished = false
instpxy.uninstall(appid) do |name, status|
  p [name, status]
  finished = (status["Error"] or status["Status"] == "Complete")
end

until finished
  #nop
end
