#!/usr/bin/env ruby

require 'bundler/setup'
require 'idevice'

outname = ARGV.shift || "iscreenshot.tiff"

begin
  sshotr = Idevice::ScreenShotrClient.attach()
rescue Idevice::LockdownError
  $stderr.puts "[-] Error: unable to connect to screenshotr",
               "    Hint: the DeveloperTools dmg must be mounted on device"
  exit(1)
end

image = sshotr.take_screenshot
ret = File.open(outname, "w") {|f| f.write image }
puts "[+] wrote #{ret} bytes to #{outname}"
exit(0)
