#!/usr/bin/env ruby

require 'bundler/setup'
require 'idevice'

outname = ARGV.shift || "iscreenshot.tiff"
idev = Idevice::Idevice.attach

imgmnt = Idevice::ImageMounterClient.attach(idevice:idev)
if imgmnt.is_mounted?("Developer")
  sshot = Idevice::ScreenShotrClient.attach(idevice:idev).take_screenshot
  ret = File.open(outname, "w") {|f| f.write sshot }
  puts "[+] wrote #{ret} bytes to #{outname}"
  exit(0)
else
  $stderr.puts "[-] Error: cannot a take screenshot without the DeveloperTools dmg mounted on device"
  exit(1)
end
